name: flutter_guide
description: Training project
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  auto_route: ^5.0.4
  dio: ^4.0.6
  elementary: ^1.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  logger: ^1.1.0
  provider: ^6.0.5
  surf_logger: ^1.1.0
  swipe_refresh: ^1.0.2

dev_dependencies:
  auto_route_generator: ^5.0.2
  # Code generation
  build_runner: ^2.3.0
  dart_code_metrics: ^4.19.2
  elementary_test: ^1.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  intl_utils: ^2.7.0
  # Linter rules
  surf_lint_rules: ^1.5.0

environment:
  sdk: '>=2.18.5 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  class_name: AppTranslations
  main_locale: ru
  arb_dir: lib/features/translations/service/arb
  output_dir: lib/features/translations/service/generated
