name: Flutter QC

on: 
  pull_request:
    branches: [main]
    paths-ignore: 
      - ".vscode/**"
      - ".idea/**"
      - ".dart_tool/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
      - name: Downloads all project dependencies
        run: flutter pub get
      - name: Finds all warnings and errors in project
        run: flutter analyze
      - name: Builds Android app file
        run: flutter build apk --release