name: Flutter QC

on: 
  pull_request:
    branches: [main]
    paths-ignore: 
      - ".vscode/**"
      - ".idea/**"
      - ".dart_tool/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
      - uses: dart-lang/setup-dart@v1
      - name: Setup secrets in the project
        run: dart run scripts/insert_secrets.dart $YANDEX_MAP_KIT_API_KEY
        env:
          YANDEX_MAP_KIT_API_KEY: ${{ secrets.YANDEX_MAP_KIT_API_KEY }}
      - name: Downloads all project dependencies
        run: flutter pub get
      - name: Finds all warnings and errors in project
        run: flutter analyze
      - name: Runs tests for this project
        run: flutter test
      - name: Builds Android app file
        run: flutter build apk --flavor prod --target "lib/main_production.dart" 